spring.application.name=sistema_clinico
spring.datasource.url=jdbc:mysql://localhost:3306/bd_clinica?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=user_clinica
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automaticamente ejecutara la aplicacion
spring.jpa.hibernate.ddl-auto=none
# Indica cuando aplico una cosulta en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#tiempo de expiracion de login
security.jwt.expiration-minutes=30
#clave segura que solo el back sabe
security.jwt.secret-key=bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj

